import type { z } from 'zod';
import type { entitySchema, statementSchema, payloadSchema, refSchema, kindSchema } from './schema';
export type Kind=z.infer<typeof kindSchema>;
export type Ref=z.infer<typeof refSchema>;
export type Entity=z.infer<typeof entitySchema>;
export type Statement=z.infer<typeof statementSchema>;
export type Payload=z.infer<typeof payloadSchema>;
export type Base=Pick<Entity,'id'|'revision'|'status'|'review'|'spoilerWorkIds'>;
export type Status=Base['status'];
export type Review=NonNullable<Base['review']>;
export type GuardedText=Entity['title'];
export type Dataset={entities:Entity[];statements:Statement[]};
export type Issue={code:string;ref:string;message:string};
export type PublicPayload=Exclude<Payload,{type:'evidence'|'asset'}>|Omit<Extract<Payload,{type:'evidence'}>,'verificationNote'>|(Omit<Extract<Payload,{type:'asset'}>,'path'|'checkedBy'> & {publicUrl:string});
export type PublicEntity=Omit<Entity,'review'|'revision'|'status'|'payload'> & {payload:PublicPayload};
export type PublicStatement=Omit<Statement,'review'|'revision'|'status'|'markdown'> & {html:string};
export type PublishedGraph={entities:PublicEntity[];statements:PublicStatement[]};
export type PageRef={kind:'work'|'background'|'person';id:string};
export type PayloadGroup={token:string;requires:string[];graph:PublishedGraph};
export type Publication={base:PublishedGraph;groups:PayloadGroup[]};
