import {renderPlaceMap,renderPlaceList,renderTimeline} from './exploration';
import type {PageView} from './types';
export const escapeHtml=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const kinds:Record<string,string>={history:'歴史・背景',depiction:'作中の描写',statement:'本人の発言',interpretation:'編集者の解釈'};
const relations:Record<string,string>={context:'背景との接点',participation:'作品への参加',inspiration:'明示された着想源',adaptation:'史実・原典との対応','shared-background':'共通する背景',comparison:'編集者の比較',location:'場所',chronology:'出来事'};
export function renderReferences(view:PageView){return view.references.length?`<section class="references" aria-labelledby="references-title"><h2 id="references-title">出典・資料</h2><ol>${view.references.map((r,i)=>`<li id="evidence-${escapeHtml(r.id)}" tabindex="-1"><span class="meta">出典${i+1}</span><h3>${escapeHtml(r.title)}</h3><p>${escapeHtml(r.author)}<br>${escapeHtml(r.bibliography??'')}<br>該当箇所：${escapeHtml(r.locator)}<br>参照日：${escapeHtml(r.accessedOn)}</p>${r.url?`<a href="${escapeHtml(r.url)}" rel="noreferrer">資料を開く（外部サイト）</a>`:''}</li>`).join('')}</ol></section>`:'';}
function citations(ids:string[],view:PageView){return ids.map(id=>{const i=view.references.findIndex(x=>x.id===id);return i<0?'':`<a class="citation" href="#evidence-${escapeHtml(id)}">出典${i+1}</a>`;}).join(' ');}
export function renderLinks(view:PageView){return view.links.length?`<section><h2>つながる作品・背景・人物</h2><ul class="related-list">${view.links.map(l=>`<li><span class="meta">${escapeHtml(relations[l.kind]??l.kind)}</span><h3><a href="${escapeHtml(l.href)}">${escapeHtml(l.label)}</a></h3><div class="relation-reason">${l.reason}</div>${citations(l.evidenceIds,view)}</li>`).join('')}</ul></section>`:'';}
export function renderPageBody(view:PageView):string{
 const groups=new Map<string,typeof view.blocks>();
 for(const b of view.blocks){const heading=b.kind==='statement'?'本人の発言':b.kind==='interpretation'?'編集者の解釈':b.section==='connection'?'作品との接点':b.section==='production'?'制作の背景':b.section==='acting'?'役作り':b.section==='summary'?'作品の概要':'背景の説明';const groupKey=heading+(b.workLabels.length?'：'+b.workLabels.join('・'):'');groups.set(groupKey,[...(groups.get(groupKey)??[]),b]);}
 return `<p class="reading-time">読む目安 ${view.readingMinutes}分</p>${[...groups].map(([heading,blocks])=>`<section class="prose"><h2>${escapeHtml(heading)}</h2>${blocks.map(b=>`<article id="statement-${escapeHtml(b.id)}"><span class="kind-label">${kinds[b.kind]}</span><div>${b.html}</div>${b.quote?`<p class="meta">${escapeHtml(b.quote)}</p>`:''}<div>${citations(b.evidenceIds,view)}</div></article>`).join('')}</section>`).join('')}${renderLinks(view)}${view.pageKind==='work'&&!view.links.some(l=>l.targetKind==='work')?'<p class="empty-state">関連作品はまだ掲載していません</p>':''}${view.places.length?`<section id="places"><h2>場所から読む</h2>${renderPlaceMap(view)}${renderPlaceList(view)}</section>`:""}${renderTimeline(view)}${renderReferences(view)}`;
}
